### ISSUE TITLE
Feature Request: Allow filtering cross world prices for HQ

### ISSUE THREAD

**Issue by kotarou3** [viion/marketboard#6]
...so only the HQ prices are listed in the cross-world summary.

Would be nice for food/pots/equipment, where NQ price is pretty irrelevant.

**Comment by Scrxtchy** [comment]
> ...so only the HQ prices are listed in the cross-world summary.

There is no visual representation if an item is HQ or not, but the list does return NQ items
The data exists to know if an item is HQ or NQ, so filtering is also an option, but is lacked. So I hope that this has been considered in V2

**Comment by viion** [comment]
In v2 you have access to the full market board per server, viewing everything you can for your home, for your whole DC. In this you can tick a box to ignore NQ or HQ (your choice). The summary that provides statistics, figures and graphs will be split by NQ/HQ as well.

**Comment by kotarou3** [comment]
Solved in v2
